/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-09-03 07:09:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.studycafe.model.dto.Page;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/gaeunlee/Documents/baby/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/studyCafe/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1463059995000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.studycafe.model.dto.Page");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\r\n");
      out.write("<link href=\"/studyCafe/resources/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"/studyCafe/resources/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/studyCafe/resources/js/carousel.js\"></script>\r\n");
      out.write("<script src=\"//developers.kakao.com/sdk/js/kakao.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <title> 스터디 카페 </title>\r\n");
      out.write("</head>\r\n");
      out.write("<body data-spy=\"scroll\">\r\n");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- carousel START -->\r\n");
      out.write("\t\t<div class= \"carousel slide\" id=\"featured\" data-toggle=\"true\" data-ride=\"carousel\">\t\t\t\t\r\n");
      out.write("\t\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t<li data-target = \"#featured\" data-slide-to=\"0\"></li>\r\n");
      out.write("\t\t\t\t<li data-target = \"#featured\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t\t<li data-target = \"#featured\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t\t<li data-target = \"#featured\" data-slide-to=\"3\"></li>\r\n");
      out.write("\t\t\t\t<li data-target = \"#featured\" data-slide-to=\"4\"></li>\r\n");
      out.write("\t\t\t</ol>\r\n");
      out.write("\t<!-- image list START -->\t\t\t\t\t\r\n");
      out.write("\t\t<div class=\"carousel-inner\">\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<div class=\"item active\" >\r\n");
      out.write("\t\t\t\t<img  style=\"height: 550px; width: 1600px\" src=\"/studyCafe/resources/image/carousel/study1.jpg\" alt=\"first\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<h1 style=\"font-weight: bold\">함께 공부해요!</h1>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-size: large;\">함께 공부해요!함께 공부해요!함께 공부해요!함께 공부해요!함께 공부해요!</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t<div  class=\"item\">\r\n");
      out.write("\t\t\t\t<img style=\"height: 550px; width: 1600px\" src=\"/studyCafe/resources/image/carousel/study2.jpg\" alt=\"second\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<h1 style=\"font-weight: bold\">다양한 관심사의 스터디 그룹!</h1>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-size: large;\">다양한 스터디 그룹!다양한 스터디 그룹!다양한 스터디 그룹!다양한 스터디 그룹!다양한 스터디 그룹!</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t<img style=\"height: 550px; width: 1600px\" src=\"/studyCafe/resources/image/carousel/study3.JPG\" alt=\"third\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<h1 style=\"font-weight: bold\">스터디 자료는 내 공부방에서</h1>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-size: large;\">스터디 자료는 내 공부방에서스터디 자료는 내 공부방에서스터디 자료는 내 공부방에서스터디 자료는 내 공부방에서</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t<img style=\"height: 550px; width: 1600px\" src=\"/studyCafe/resources/image/carousel/study4.jpg\" alt=\"fourth\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<h1 style=\"font-weight: bold\">체계적인 스터디 플랜 </h1>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-size: large;\">체계적인 스터디 플랜 체계적인 스터디 플랜 체계적인 스터디 플랜 체계적인 스터디 플랜 체계적인 스터디 플랜 </p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t<img style=\"height: 550px; width: 1600px\" src=\"/studyCafe/resources/image/carousel/study5.jpg\" alt=\"fifth\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<h1 style=\"font-weight: bold\">멘토 추천! </h1>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-size: large;\">멘토 추천! 멘토 추천! 멘토 추천! 멘토 추천! 멘토 추천! 멘토 추천! 멘토 추천! 멘토 추천! </p>\r\n");
      out.write("\t\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<!-- image list END -->\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t<a class=\"left carousel-control\" href =\"#featured\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t<span class=\"glyphicon glyphicon-chevron-left\"></span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t<a class=\"right carousel-control\" href =\"#featured\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("\t\t\t<span class=\"glyphicon glyphicon-chevron-right\"></span>\r\n");
      out.write("\t\t\t</a>\t\t\t\t\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("<!-- carousel END-->\r\n");
      out.write("  <br/>     <br/>   \r\n");
      out.write("  <div class=\"jumbotron\" style=\"font-weight: bold;\" >\r\n");
      out.write("  \r\n");
      out.write("   <h2 align=\"center\" style=\"font-weight: bold;\">Our Mission</h2>   \r\n");
      out.write("   <br/>   \r\n");
      out.write("   <div align=\"center\">\r\n");
      out.write("\t\t     \t <p> pply the wisdom garnered in the centuries old tradition of veterinary medicine, to find the safest treatments and&nbsp;cures.</p>\r\n");
      out.write("\t\t      \t <p> receives the most appropriate care at crucial milestones. We want to give your pet a long and healthy&nbsp;life.</p>\r\n");
      out.write("    <p> receives the most appropriate care at crucial milestones. We want to give your pet a long and healthy&nbsp;life.</p>\r\n");
      out.write("   \t</div>\r\n");
      out.write("   \t   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br/><br/><br/>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div id=\"pageContainer\">\r\n");
      out.write("  <div class=\"row\" id=\"studyCategory\">\r\n");
      out.write("    <section class=\"page col-md-12\">\r\n");
      out.write("      <h2 style=\"font-weight: bold;\">스터디 카테고리</h2>\r\n");
      out.write("      <div  class=\"row\" >\r\n");
      out.write("        \r\n");
      out.write("\t        <section data-category=\"1\" class=\"col-md-4\">\r\n");
      out.write("\t        <img id=\"life\"  class=\"icon\" src=\"/studyCafe/resources/image/lifestyle.png\" height=\"170px\" width=\"170px\" align=\"center\" alt=\"Icon\">\r\n");
      out.write("\t          <h3 >라이프 스타일 </h3> \r\n");
      out.write("\t          \r\n");
      out.write("\t               \r\n");
      out.write("\t          <p>We offer specialized care forther exotic pets.</p>\r\n");
      out.write("\t        </section>        \r\n");
      out.write("\t        \r\n");
      out.write("\t        <section data-category=\"2\" class=\"col-md-4\">\r\n");
      out.write("\t        <img id=\"english\"  class=\"icon\" src=\"/studyCafe/resources/image/a.png\" height=\"170px\" width=\"170px\" align=\"middle\" alt=\"Icon\">\r\n");
      out.write("\t          <h3  >영어 </h3>\r\n");
      out.write("\t          <p>Our therapeutic grooming treatments hhallenging skin conditions.</p>\r\n");
      out.write("\t        </section>       \r\n");
      out.write("\t        \r\n");
      out.write("\t        <section data-category=\"3\" class=\"col-md-4\">\r\n");
      out.write("\t        <img id=\"foreign\"  class=\"icon\" src=\"/studyCafe/resources/image/foreignL.png\" height=\"170px\" width=\"170px\" align=\"middle\" alt=\"Icon\">\r\n");
      out.write("\t          <h3 >외국어 </h3>\r\n");
      out.write("\t          <p>Our  therapeutic grooming treatments helpkin conditions.</p>\r\n");
      out.write("\t        \r\n");
      out.write("\t        </section>         \r\n");
      out.write("      </div>\r\n");
      out.write("<br/><br/><br/><br/>   \r\n");
      out.write("     \r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("      \r\n");
      out.write("\t        <section data-category=\"4\"  class=\"col-md-4\">\r\n");
      out.write("\t        <img id=\"computer\"  class=\"icon\" src=\"/studyCafe/resources/image/computer.png\" height=\"170px\" width=\"170px\" align=\"middle\" alt=\"Icon\">\r\n");
      out.write("\t          <h3 >컴퓨터 </h3>\r\n");
      out.write("\t          <p>Wellness and senior exams, ultrasound, x-ray,  few of our general health services.</p>\r\n");
      out.write("\t        </section>    \r\n");
      out.write("\t            \r\n");
      out.write("\t        <section data-category=\"5\" class=\"col-md-4\">\r\n");
      out.write("\t        <img id=\"design\"   class=\"icon\" src=\"/studyCafe/resources/image/design.png\" height=\"170px\" width=\"170px\" align=\"middle\" alt=\"Icon\">\r\n");
      out.write("\t          <h3 >디자인 </h3>\r\n");
      out.write("\t          <p>Let our nutrition experts review your pet's diet and prescribeth.</p>\r\n");
      out.write("\t        </section>  \r\n");
      out.write("\t          \r\n");
      out.write("\t        <section data-category=\"6\" class=\"col-md-4\">\r\n");
      out.write("\t        <img id=\"certification\"   class=\"icon\" src=\"/studyCafe/resources/image/certification.png\" height=\"170px\" width=\"170px\" align=\"middle\" alt=\"Icon\">\r\n");
      out.write("\t          <h3 >국가고시 </h3>\r\n");
      out.write("\t          <p>Let our nutrition experts review and disease prevention.</p>\r\n");
      out.write("\t        </section> \r\n");
      out.write("\t             \r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    <br/><br/><br/><br/> \r\n");
      out.write("\t      \r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        \r\n");
      out.write("        <section  data-category=\"7\" class=\"col-md-4\">\r\n");
      out.write("\t        <img id=\"job\"  class=\"icon\" src=\"/studyCafe/resources/image/job.png\" height=\"170px\" width=\"170px\" align=\"middle\" alt=\"Icon\">\r\n");
      out.write("          <h3>취업 </h3>\r\n");
      out.write("          <p>We offer the latest advances in safe and effective </p>\r\n");
      out.write("        </section>        \r\n");
      out.write("        \r\n");
      out.write("        <section data-category=\"8\" class=\"col-md-4\">\r\n");
      out.write("\t        <img  id=\"music\"   class=\"icon\" src=\"/studyCafe/resources/image/music.png\" height=\"170px\" width=\"170px\" align=\"middle\" alt=\"Icon\">\r\n");
      out.write("          <h3>음악공연 </h3>\r\n");
      out.write("          <p>Our veterinarians are experienced in modern vaccination .</p>\r\n");
      out.write("        </section>        \r\n");
      out.write("        \r\n");
      out.write("        <section data-category=\"9\" class=\"col-md-4\">\r\n");
      out.write("\t        <img id=\"sports\"    class=\"icon\" src=\"/studyCafe/resources/image/sports.png\" height=\"170px\" width=\"170px\" align=\"middle\" alt=\"Icon\">\r\n");
      out.write("          <h3>스포츠 </h3>\r\n");
      out.write("          <p>Our veterinarians are experienced in modern </p>\r\n");
      out.write("        </section> \r\n");
      out.write("               \r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </div>\r\n");
      out.write("<br/><br/><br/><br/><br/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <section id=\"staff\" class=\"page col-sm-12\">\r\n");
      out.write("      <h2 style=\"font-weight: bold\">추천 스터디 멘토</h2>\r\n");
      out.write("      <div class=\"row\" align=\"center\">\r\n");
      out.write("        <br/><br/><br/>\r\n");
      out.write("        <section class=\"col-sm-4\">\r\n");
      out.write("        <img class=\"img-circle\" src=\"/studyCafe/resources/image/teacher1.jpg\"  height=\"170px\" width=\"170px\" align=\"middle\" alt=\"Icon\">\r\n");
      out.write("          <br/> <br/>\r\n");
      out.write("          <h3>김 이지</h3>\r\n");
      out.write("          <br/><br/>\r\n");
      out.write("          <p>Dr. Winthrop is the guardian of Missy, a three-year old Llaso mix, who he adopted at the shelter. Dr. Winthrop is passionate about spay and neuter and pet adoption, and works tireless hours outside the clinic, performing free spay and neuter surgeries for the shelter.</p>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"col-sm-4\">\r\n");
      out.write("         <img class=\"img-circle\" src=\"/studyCafe/resources/image/teacher2.jpeg\"  height=\"170px\" width=\"170px\" align=\"middle\" alt=\"Icon\">\r\n");
      out.write("          <br/> <br/>\r\n");
      out.write("          <h3>유 조이 </h3>\r\n");
      out.write("          <br/><br/>\r\n");
      out.write("          <p>Dr. Chase spends much of her free time helping the local rescue organization find homes for animals, such as Kibbles - a Maine Coon Cat who is part of the large Chase household, including two dogs, three cats, and a turtle.</p>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"col-sm-4\" >\r\n");
      out.write("         <img class=\"img-circle\" src=\"/studyCafe/resources/image/teacher3.jpg\"  height=\"170px\" width=\"170px\" align=\"middle\" alt=\"Icon\">\r\n");
      out.write("          <br/> <br/>\r\n");
      out.write("          <h3>임 해피</h3>\r\n");
      out.write("          <br/><br/>\r\n");
      out.write("          <p>Leroy walked into Dr. Sanders front door when he was moving into a new house. After searching for weeks for Leroy's guardians, he decided to make Leroy a part of his pet family, and now has three cats.</p>\r\n");
      out.write("        </section>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("<br/><br/><br/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <section id=\"testimonials\" class=\"page col-sm-12\">\r\n");
      out.write("      <h2 style=\"font-weight: bold\">스터디 멤버 후기 </h2>\r\n");
      out.write("      <br/><br/><br/>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <section class=\"col-sm-6\">\r\n");
      out.write("          <blockquote>\r\n");
      out.write("          <p>During the summer, our rabbit, Tonto, began to have severe redness and itching on his belly and feet. Through diagnostic testing, we learned that Tonto is severely allergic to over a dozens kinds of grass pollens. We've now been doing allergy injections for several months, and his itching and redness have nearly gone away.</p>\r\n");
      out.write("          <footer>Jane H.</footer>\r\n");
      out.write("          </blockquote>\r\n");
      out.write("        </section>\r\n");
      out.write("        <br/><br/>\r\n");
      out.write("        <section class=\"col-sm-6\">\r\n");
      out.write("          <blockquote>\r\n");
      out.write("            <p>When Samantha, our Siamese cat, began sleeping all the time and urinating excessively, we brought her to see the specialists at Wisdom. After running a blood test, Dr. Winthrop confirmed what we all feared - Samantha was showing signs of diabetes. The doctor put us on a daily routine to provide Samantha insulin injections, and showed us how to administer the shots.</p>\r\n");
      out.write("            <footer>The McPhersons</footer>\r\n");
      out.write("          </blockquote>\r\n");
      out.write("        </section>\r\n");
      out.write("      </div>\r\n");
      out.write("      <br/><br/>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <section class=\"col-sm-6\">\r\n");
      out.write("          <blockquote>\r\n");
      out.write("            <p>The staff at Wisdom worked tirelessly to determine why our three-year old Golden Retriever, Roxie, started going into sudden kidney failure. They stabilized her and provided fluids until her kidneys were again functioning normally. We learned just how toxic grapes and raisins are to pets, and Roxie is no longer allowed to roam unattended in the orchard.</p>\r\n");
      out.write("            <footer>John B</footer>\r\n");
      out.write("          </blockquote>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"col-sm-6\">\r\n");
      out.write("          <blockquote>\r\n");
      out.write("            <p>Wisdom Pet Medicine is the only clinic around that will even book pet fish for appointments. When our 13-year old Comet goldfish, McAllister, turned from silvery white to an angry red, we called around, urgently trying to find a veterinarian who could help. Wisdom not only got us in the same day, but also was able to diagnose McAllister as having a severe case of septicemia.</p>\r\n");
      out.write("            <footer>Lorraine S</footer>\r\n");
      out.write("          </blockquote>\r\n");
      out.write("        </section>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  </div><!-- row -->   \r\n");
      out.write("</div><!-- content container -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("/* 로그인 실패 때, 로그인 실패 메시지를 전달해 주는 제이쿼리 ,아작스   */\r\n");
      out.write("/* 로그인 실패 때, 로그인 실패 메시지를 전달해 주는 제이쿼리 ,아작스   */\r\n");
      out.write(" /* 로그인 실패 때, 로그인 실패 메시지를 전달해 주는 제이쿼리 ,아작스   */\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#btnLogin').on('click', function(event){\r\n");
      out.write("\t\t\t$( '#loginResult' ).text('');\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"/studyCafe/account/login.action\",\r\n");
      out.write("\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\tdata:$( '#frmLogin' ).serialize(),\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tsuccess: function(data,status,xhr){\r\n");
      out.write("\t\t\t\t\tif(data==\"success\"){\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"/studyCafe/home.action\";\r\n");
      out.write("\t\t\t\t\t}else if(data==\"fail\"){\r\n");
      out.write("\t\t\t\t\t\t$('#loginResult' ).text('로그인 실패하셨습니다. 다시 시도해 주세요');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t})\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#btnRegister').on('click', function(event){\r\n");
      out.write("\t\t\tlocation.href='/studyCafe/member/term.action';\r\n");
      out.write("\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t$('#studyCategory section[data-category]').on('mouseover', function(event){\r\n");
      out.write("\t\t\t$(this).css('border',' #a3a3c2 solid 2px')\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('#studyCategory section[data-category]').on('mouseout', function(event){\r\n");
      out.write("\t\t\t$(this).css('border','0')\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('#studyCategory section[data-category]').on('click', function(event){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tlocation.href='/studyCafe/board/list2.action?bigCategory='+$(this).attr('data-category');\r\n");
      out.write("\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t /* 로그인 실패 때, 로그인 실패 메시지를 전달해 주는 제이쿼리 ,아작스   */\r\n");
      out.write("\t/* 로그인 실패 때, 로그인 실패 메시지를 전달해 주는 제이쿼리 ,아작스   */\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer\"></div>\r\n");
      out.write("\t\r\n");
      out.write("<form id=\"frmLogin\" action=\"/studyCafe/account/login.action\" method=\"post\">\r\n");
      out.write("<!-- -----------------------------------Modal----------------------------------- -->\r\n");
      out.write("<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\"><span aria-hidden=\"true\">&times;</span><span class=\"sr-only\">Close</span></button>\r\n");
      out.write("        <h4 class=\"modal-title\" id=\"myModalLabel\" style=\"font-weight:bolder;color:black;\" align=\"left\" ><span class=\"glyphicon glyphicon-user\"></span>&nbsp;&nbsp;로그인</h4>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\" align=\"center\">\r\n");
      out.write("      <p> <!-- 여기는 내용이 들어 가는 곳 --> <input type=\"button\" class=\"btn btn-primary\" id=\"login\" style=\"width:200px; height:60px\" value=\"페이스북 계정으로 로그인\"> </p>\r\n");
      out.write("      <a id=\"kakao-login-btn\"></a>\r\n");
      out.write("\t\t<!-- <a href=\"#\" onclick=\"ktout()\">카카오 로그아웃</a> -->\r\n");
      out.write("      <div class=\"signup-or-separator\">\r\n");
      out.write("      \t<span style=\"position:'absolute';top:500;\" >or</span>\r\n");
      out.write("      \t<hr>\r\n");
      out.write("      </div>\r\n");
      out.write("      <p><!-- 여기는 내용이 들어 가는 곳 --><input class=\"form-control\"  name=\"memberId\" type=\"text\" style=\"width:350px; height:60px\"  placeholder=\"아이디\"> </p>\r\n");
      out.write("      <p><!-- 여기는 내용이 들어 가는 곳 --><input class=\"form-control\" name=\"passwd\" type=\"password\" style=\"width:350px; height:60px\"  placeholder=\"비밀번호\"> </p>\r\n");
      out.write("      <p> <input type=\"checkbox\" value=\"로그인 유지 \" id=\"keepLogin\">로그인 유지</p>\r\n");
      out.write("      \r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"loginResult\" style=\"text-align: center; color:red\"></div>\r\n");
      out.write("      <div class=\"modal-footer\" >\r\n");
      out.write("        <button type=\"button\" id=\"btnLogin\" class=\"btn btn-danger\">로그인</button>\r\n");
      out.write("        <input type=\"button\" id=\"btnRegister\" class=\"btn btn-warning\" value=\"회원가입\"><!-- 변경 사항 저장 -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </div> <!-- 모달 콘텐츠 -->\r\n");
      out.write("  </div> <!-- 모달 다이얼로그 -->\r\n");
      out.write("</div> <!-- 모달 전체 윈도우 -->\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("  \r\n");
      out.write("  //<![CDATA[\r\n");
      out.write("    // 사용할 앱의 JavaScript 키를 설정해 주세요.\r\n");
      out.write("    Kakao.init('9bd78588adb541ca67caac077c742ab9');\r\n");
      out.write("    // 카카오 로그인 버튼을 생성합니다.\r\n");
      out.write("    Kakao.Auth.createLoginButton({\r\n");
      out.write("      container: '#kakao-login-btn',\r\n");
      out.write("      success: function(authObj) {\r\n");
      out.write("        // 로그인 성공시, API를 호출합니다.\r\n");
      out.write("        Kakao.API.request({\r\n");
      out.write("          url: '/v1/user/me',\r\n");
      out.write("          success: function(res) {\r\n");
      out.write("            alert(JSON.stringify(res));\r\n");
      out.write("          },\r\n");
      out.write("          fail: function(error) {\r\n");
      out.write("            alert(JSON.stringify(error));\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("      },\r\n");
      out.write("      fail: function(err) {\r\n");
      out.write("        alert(JSON.stringify(err));\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  //]]>\r\n");
      out.write("  function ktout(){\r\n");
      out.write("\t  \r\n");
      out.write("\t  kakao.Auth.logout(function(){\r\n");
      out.write("\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\tlocation.href= \"/studyCafe/home.action\"\r\n");
      out.write("\t\t},1000);  \r\n");
      out.write("\t  });\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fimport_005f0.setParent(null);
    // /WEB-INF/views/index.jsp(24,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f0.setUrl("/WEB-INF/views/include/header.jsp");
    int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
      if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fimport_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
    }
    return false;
  }
}
