/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-09-03 07:36:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.studycafe.model.dto.Member;

public final class writeform2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/gaeunlee/Documents/baby/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/studyCafe/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1463059995000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.studycafe.model.dto.Member");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<title>스터디 등록</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/ui/1.11.4/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"Stylesheet\" href=\"/studyCafe/resources/styles/input2.css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/studyCafe/resources/js/HuskyEZCreator.js\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#datepicker1\").datepicker({\r\n");
      out.write("\t\t\tdateFormat : 'yy-mm-dd'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"pageContainer\">\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div style=\"padding-top: 30px;\">\r\n");
      out.write("\t\t\t<div id=\"inputcontent\">\r\n");
      out.write("\t\t\t\t\t<div class=\"inputsubtitle\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"font-size: 28px; margin-bottom: 15px; text-align: center\">스터디 등록</div>\r\n");
      out.write("\t\t\t\t\t<form action=\"write.action\" method=\"post\"\r\n");
      out.write("\t\t\t\t\t\tenctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"memberNo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginuser.memberNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' />\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"height: 30px\">등록인</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"hidden\" name=\"uploader\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginuser.memberId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' /> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginuser.memberId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"title\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"스터디 룸의 제목을 입력하세요\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 580px; height: 30px\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>카테고리</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select name=\"smallCategoryNo\" class=\"selectpicker\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 30px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option disabled=\"disabled\" selected=\"selected\">카테고리를\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t선택하세요</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<optgroup label=\"라이프스타일\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"101\">육아</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"102\">반려동물</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"103\">금융/재테크</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"104\">상담/컨설팅</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"105\">건강/웰빙</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"106\">사주/타로</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"107\">독서/글쓰기</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"114\">라이프스타일 기타</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<optgroup label=\"영어\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"201\">토익</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"202\">토플</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"203\">탭스</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"204\">토익/오픽</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"205\">영어회화</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"206\">작문/독해</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"207\">미드정복</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"208\">영어 기타</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<optgroup label=\"외국어\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"301\">중국어</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"302\">일본어</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"303\">독일어</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"305\">태국어</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"306\">스페인어</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"307\">러시아어</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"308\">프랑스어</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"310\">외국어 기타</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<optgroup label=\"컴퓨터\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"401\">응용프로그래밍</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"402\">웹프로그래밍</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"403\">모바일프로그래밍</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"406\">문서작성/편집</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<optgroup label=\"디자인\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"501\">웹/모바일디자인</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"502\">일러스트/삽화</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"503\">광고/영상</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<optgroup label=\"국가고시/공무원\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"601\">행정</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"602\">교육</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"603\">경찰</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<optgroup label=\"취업\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"701\">자소서/면접</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"702\">인적성</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"705\">기업공채</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<optgroup label=\"음악/공연\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"805\">밴드</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"806\">국악</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<optgroup label=\"스포츠\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"901\">축구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"902\">야구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"904\">테니스</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>목표</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"height: 50px\"><label class=\"checkbox-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" value=\"자기개발\" id=\"purpose\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"purpose\" />자기개발\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> <label class=\"checkbox-inline\"> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"자격증준비\" id=\"purpose\" name=\"purpose\" />자격증준비\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> <label class=\"checkbox-inline\"> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"취미생활\t\" id=\"purpose\" name=\"purpose\" />취미생활\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> <label class=\"checkbox-inline\"> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"업무시킬UP\" id=\"purpose\" name=\"purpose\" />업무시킬UP\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> <label class=\"checkbox-inline\"> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"건강/다이어트\" id=\"purpose\" name=\"purpose\" />건강/다이어트\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> <label class=\"checkbox-inline\"> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"기타\" id=\"purpose\" name=\"purpose\" />기타\r\n");
      out.write("\t\t\t\t\t\t\t\t</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>모집 마감일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"datepicker1\" name=\"closeDate\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 30px; border: 2px solid #dddddd;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"모집마감 날짜(yyyy-MM-dd)\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>기간</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select class=\"btn btn-primary dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"period\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option disabled=\"disabled\" selected=\"selected\">진행 기간</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">1개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2\">2개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"3\">3개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"4\">4개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"5\">5개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"6\">6개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"7\">7개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"8\">8개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"9\">9개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"10\">10개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"11\">11개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"12\">12개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"12이상\">1년 이상</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>횟수</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"frequency\" placeholder=\"예: 3주, 3개월 \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 100px; height: 25px\" /> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option disabled=\"disabled\" selected=\"selected\">주기</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"주\">주</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"월\">월</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>모집인원 수</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"memberCount\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 100px; height: 30px\" />명</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>장소</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"place\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 100px; height: 30px\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- boardimage 등록 부분 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>사진 등록</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"file\" name=\"boardimage\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 650px; height: 25px\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>설명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><textarea name=\"content\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"ir1\" rows=\"10\" cols=\"100\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 100%; height: 412px; display: none;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"buttons\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"btn btn-default\" type=\"submit\" value=\"자료등록\" \r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"btnSubmit\" /> <input class=\"btn btn-default\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"취소\" \r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"location.href='/studyCafe/home.action';\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar oEditors = [];\r\n");
      out.write("\r\n");
      out.write("\t\t// 추가 글꼴 목록\r\n");
      out.write("\t\t//var aAdditionalFontSet = [[\"MS UI Gothic\", \"MS UI Gothic\"], [\"Comic Sans MS\", \"Comic Sans MS\"],[\"TEST\",\"TEST\"]];\r\n");
      out.write("\r\n");
      out.write("\t\tnhn.husky.EZCreator.createInIFrame({\r\n");
      out.write("\t\t\toAppRef : oEditors,\r\n");
      out.write("\t\t\telPlaceHolder : \"ir1\",\r\n");
      out.write("\t\t\tsSkinURI : \"/studyCafe/resources/SmartEditor2Skin.html\",\r\n");
      out.write("\t\t\thtParams : {\r\n");
      out.write("\t\t\t\tbUseToolbar : true, // 툴바 사용 여부 (true:사용/ false:사용하지 않음)\r\n");
      out.write("\t\t\t\tbUseVerticalResizer : true, // 입력창 크기 조절바 사용 여부 (true:사용/ false:사용하지 않음)\r\n");
      out.write("\t\t\t\tbUseModeChanger : true, // 모드 탭(Editor | HTML | TEXT) 사용 여부 (true:사용/ false:사용하지 않음)\r\n");
      out.write("\t\t\t\t//aAdditionalFontList : aAdditionalFontSet,\t\t// 추가 글꼴 목록\r\n");
      out.write("\t\t\t\tfOnBeforeUnload : function() {\r\n");
      out.write("\t\t\t\t\t//alert(\"완료!\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, //boolean\r\n");
      out.write("\t\t\tfOnAppLoad : function() {\r\n");
      out.write("\t\t\t\t//예제 코드\r\n");
      out.write("\t\t\t\t//oEditors.getById[\"ir1\"].exec(\"PASTE_HTML\", [\"로딩이 완료된 후에 본문에 삽입되는 text입니다.\"]);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tfCreator : \"createSEditor2\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction pasteHTML() {\r\n");
      out.write("\t\t\tvar sHTML = \"<span style='color:#FF0000;'>이미지도 같은 방식으로 삽입합니다.<\\/span>\";\r\n");
      out.write("\t\t\toEditors.getById[\"ir1\"].exec(\"PASTE_HTML\", [ sHTML ]);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction showHTML() {\r\n");
      out.write("\t\t\tvar sHTML = oEditors.getById[\"ir1\"].getIR();\r\n");
      out.write("\t\t\talert(sHTML);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction submitContents(elClickedObj) {\r\n");
      out.write("\t\t\toEditors.getById[\"ir1\"].exec(\"UPDATE_CONTENTS_FIELD\", []); // 에디터의 내용이 textarea에 적용됩니다.\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 에디터의 내용에 대한 값 검증은 이곳에서 document.getElementById(\"ir1\").value를 이용해서 처리하면 됩니다.\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t\telClickedObj.form.submit();\r\n");
      out.write("\t\t\t\t/* var url = '/studyCafe/page/board/list.action?menuno=' + ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.menuNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" + '&memberpageno=' + ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberpageno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; \r\n");
      out.write("\t\t    \t$(location).attr('href', url); */\r\n");
      out.write("\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction setDefaultFont() {\r\n");
      out.write("\t\t\tvar sDefaultFont = '궁서';\r\n");
      out.write("\t\t\tvar nFontSize = 24;\r\n");
      out.write("\t\t\toEditors.getById[\"ir1\"].setDefaultFont(sDefaultFont, nFontSize);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$('#btnSubmit').on('click', function(event) {\r\n");
      out.write("\t\t\tsubmitContents(this);\r\n");
      out.write("\t\t})\r\n");
      out.write("\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fimport_005f0.setParent(null);
    // /WEB-INF/views/board/writeform2.jsp(39,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f0.setUrl("/WEB-INF/views/include/header.jsp");
    int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
      if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fimport_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
    }
    return false;
  }
}
